### ISSUE TITLE
Question on using multiple shaders. 

### ISSUE THREAD

**Issue by Ansh-Rathod** [Rahiche/leather_background#1]
Hi Raouf! I have been going through your repos and started learning about shaders. so i'm building something related to effects on photo and made some fragment shaders based on it. do you know any correct way to implement multiple shaders on one Image. like apply somekind of blur, then any other effects using other frag shader on same image. i have like 10-12 shader effects and wanna apply on the image. 

Also Thank you for making these repos open-source its been very helpful.

**Comment by Rahiche** [comment]
Hi @Ansh-Rathod 

Happy to hear that you are finding my repos useful, I have't tried exactly what you are talking about but I assume it is possible but with multiple passes.

I think the shader_buffers package by @alnitak does what you are talking about 
https://github.com/alnitak/shader_buffers

**Comment by alnitak** [comment]
Thanks @Rahiche for pointing me out! 

Yes, [shader_buffers](https://github.com/alnitak/shader_buffers) is meant to use the output of a shader and use it into one or more shaders as an input texture. Every shaders can have its uniforms, [here an example](https://github.com/alnitak/shader_buffers?tab=readme-ov-file#Layering-shaders)

**Comment by Ansh-Rathod** [comment]
Hey @Rahiche Thanks for suggesting! 

I got to know about this package a few days ago. @alnitak Also through this example it's a little hard for me to understand. like I have very simple shaders, not those animated ones. So what i'm trying to do is mainImage will be `Image.asset` then I'll apply other shaders 

My confusion with the example is how to pass values to `vec2 uSize` and `float value`

here are the two shader examples:

<details> 
 <summary>First shader</summary>

```
#version 460 core
precision highp float;

#include <flutter/runtime_effect.glsl>
out vec4 FragColor;


uniform sampler2D uSampler;
uniform vec2 uSize;
uniform float value;

void main() {
    vec2 fragCoord = FlutterFragCoord();
    vec2 uv = fragCoord/uSize;

    vec4 color = texture(uSampler, uv);
    color.g = clamp(color.g + value, 0.0, 1.0);
    FragColor = color;
}
```
</details>

<details>
<summary> second shader</summary>

```
#version 460 core
precision highp float;

#include <flutter/runtime_effect.glsl>
out vec4 FragColor;

uniform sampler2D uSampler;
uniform vec2 uSize;
uniform float size;
uniform float value;

void main() {

    vec2 fragCoord = FlutterFragCoord();
    vec2 uv = fragCoord/uSize;

    vec4 color = texture(uSampler, uv);
    float dist = distance(uv, vec2(0.5, 0.5));

    float grd = smoothstep(0.8, size * 0.799, dist * (value*0.6 + size*2.0));
    color.rgb += vec3(1.0, 1.0, 1.0) * (1.0 - grd);
    FragColor = color;
}
```
</details>

<details>
<summary>My dart code</summary>

```
  double value = 0;
  ShaderController controller = ShaderController();

  List<LayerBuffer> buffers = [];
  @override
  void initState() {
    super.initState();
    LayerBuffer mainImage = LayerBuffer(shaderAssetsName: 'shaders/white.frag');

    mainImage.channels = [
      IChannel(child: RawImage(image: decorationImageThumbnail))
    ];

    mainImage.uniforms = Uniforms([
      Uniform(
        value: value,
        name: 'value',
        range: const RangeValues(0, 1),
        defaultValue: 1,
      )
    ]);
    buffers.add(mainImage);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          ShaderBuffers(
            controller: controller,
            width: 250,
            height: 300,
            mainImage: buffers.first,
            buffers: buffers,
          ),
```
</details>

**Comment by alnitak** [comment]
@Ansh-Rathod I have added an example of your use case [here](https://github.com/alnitak/shader_buffers/blob/main/example/lib/simple_layers.dart).
If you have questions please let us use the shader_buffers issues, I have also created the repo discussion now if you wish.

**Comment by Ansh-Rathod** [comment]
Thank you for creating the simpler example! it surely resolved my confusion with passing parameters to shaders! 

Surely I will use the shader_buffers repo issues.
